### PR TITLE
Make id's read-only

### LINKED ISSUE #275: Ignore id if set in post requests
- [x] This issue/feature is not reported yet
- [x] I built the project based on the latest master
- [x] I have checked the documentation to see if there is a procedure described for this case

---

## Expected behavior

POST for service or applications ignores the id in the json provided by a user even if it has a value.

## Actual behavior

The id is used to match the db node which leads to a variety of errors.

Examples:

Does not save an application if id is set even if the response is 201
Posting a new service can merge with an application with the same id in the db.

## How can the issue be reproduced?

Use the swagger ui to post a service or application and don't delete the id field from the json.

### PR DESCRIPTION
**Pull request by Pascal157600**
Resolves #275 .

### CODE REVIEW

**Comment by davidkopp** [comment]
Why do we not completely ignore all IDs? The user of the API of MICO does not need the ID. He only needs the `shortName` and the `version` to make any operations to a MicoApplication or a MicoService.
Therefore we could just add `@JsonIgnore` to any `id` field.

**Comment by davidkopp** [comment]
Whatever your solution will be, you should consider to delete the method `getServiceById` in `ServiceController`.

**Comment by JanVetter** [comment]
> Does the test `createNewDependee` fail because of the changes in this PR?

@buehlefs Test is fixed

**Comment by JanVetter** [comment]
> Why do we not completely ignore all IDs? The user of the API of MICO does not need the ID. He only needs the `shortName` and the `version` to make any operations to a MicoApplication or a MicoService.
> Therefore we could just add `@JsonIgnore` to any `id` field.

@davidkopp We will not ignore completely the `id`s, as the `id` is the only guaranteed unique option for identifying our objects.

**Comment by JanVetter** [comment]
> Whatever your solution will be, you should consider to delete the method `getServiceById` in `ServiceController` (and the corresponding unit test that is currently ignored).

@davidkopp Currently, we will not delete the method `getServiceById` as it is used within the service controller. This method does not provide an API endpoint any longer, so it should be okay.

**Pull request merged**
